server:
  port: 1100
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: 192.168.1.200
    health-check-url-path: /actuator/health
    home-page-url-path: /actuator
    status-page-url-path: /actuator/info
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/